# _config.yml

title: "My Portfolio Site"
description: "This ePortfolio demonstrates my ability to design, develop, and enhance full-stack web applications with a strong emphasis on rich and responsive user interfaces, secure data management and cloud-based integration, algorithmic problem-solving, and efficient data handling."
author: "Daniel Gorelkin"

# Theme
theme: jekyll-theme-cayman
#jekyll-theme-cayman, jekyll-theme-minimal
#jekyll-theme-midnight, jekyll-theme-modernist
#jekyll-theme-primer, jekyll-theme-slate
#jekyll-theme-tactile, jekyll-theme-time-machine

# URL settings
url: "https://Dgoralkin.github.io"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# enable future-dated posts
future: true

# Exclude files/folders from the site build
exclude:
  # - README.md

# Social links
social_links:
  github: Dgoralkin
  linkedin: Daniel Gorelkin
