# _config.yml

title: "My Portfolio Site"
description: "A sample from my portfolio hosted on GitHub Pages"
author: "Daniel Gorelkin"

# Theme
theme: jekyll-theme-cayman
#jekyll-theme-cayman, jekyll-theme-minimal
#jekyll-theme-midnight, jekyll-theme-modernist
#jekyll-theme-primer, jekyll-theme-slate
#jekyll-theme-tactile, jekyll-theme-time-machine

# URL settings
url: "https://Dgoralkin.github.io"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# enable future-dated posts
future: true

# Exclude files/folders from the site build
exclude:
  # - README.md

# Social links
social_links:
  github: Dgoralkin
  linkedin: Daniel Gorelkin
